### ISSUE TITLE
Debugging the auth process

### ISSUE THREAD

**Issue by craigmjackson** [voegelas/guacamole-auth-pam#1]
Hello Andreas,

Thank you for your work on this extension.  I have an existing PHP application which successfully uses PAM authentication.  I am trying to integrate Guacamole into the server, and would like to use PAM for this as well.  I have looked at your source code for clues on logging, and see a thorough logging mechanism, but am unable to isolate the problem.  I have guacamole 0.9.13 and guacamole-auth-pam-0.9.13 running on Tomcat 8.5.20 on Ubuntu Server 16.04.

Unfortunately the catalina logs only provide:
22:29:33.646 [http-nio-8080-exec-10] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 10.0.0.86 for user "craig" failed.

And the kernel logs only provide:
java[27499]: pam_unix(guacamole:auth): authentication failure; logname= uid=1002 euid=1002 tty= ruser= rhost=  user=craig

Here is my unix-user-mapping.xml:
<?xml version="1.0" encoding="UTF-8"?>
<unix-user-mapping serviceName="guacamole">
    <config name="RDP Connection" protocol="rdp">
        <param name="hostname" value="10.0.0.61" />
        <param name="username" value="Administrator" />
        <param name="password" value="Password1" />
    </config>

    <config name="VNC Connection" protocol="vnc">
        <param name="hostname" value="10.0.0.61" />
        <param name="port" value="5900" />
        <param name="password" value="" />
    </config>

    <user name="USERNAME">
        <config-ref name="VNC Connection" />
    </user>
</unix-user-mapping>

I was able to connect and use the VNC viewer with Guacamole's default configuration.

Appreciate your help!
Craig Jackson
craigmjackson@gmail.com

**Comment by voegelas** [comment]
Hello Craig,

have you replaced "USERNAME" in the config file with "craig"?

Alternatively you could use a group that includes all permitted users:

```
<group name="users">
    <config-ref name="VNC Connection" />
</group>
```

Have you created the file "/etc/pam.d/guacamole"? Debian and Ubuntu fall back to "/etc/pam.d/other" if there's no PAM configuration file for Guacamole. By default the fallback file grants access, but if the file was changed access might be denied.

Kind regards,
Andreas

**Comment by craigmjackson** [comment]
/etc/pam.d/guacamole was previously created:
@include common-auth
@include common-account

I tried to edit the unix-user-mapping.xml to change USERNAME to craig and it had the same results.  I also tried with your group example and no change.  Based on the system logs, it seems that somehow the PAM portion is failing, reporting user unknown even though I'm sure it is known:
Sep 18 13:34:37 auburn unix_chkpwd[10766]: check pass; user unknown
Sep 18 13:34:37 auburn unix_chkpwd[10766]: password check failed for user (craig)
Sep 18 13:34:37 auburn java[10468]: pam_unix(guacamole:auth): authentication failure; logname= uid=1002 euid=1002 tty= ruser= rhost=  user=craig

The group example would be awesome, even the default auth lacks grouping.

**Comment by voegelas** [comment]
If shadow passwords are used, the "tomcat8" user needs to be added to the "shadow" group.

```
adduser tomcat8 shadow
systemctl restart tomcat8
```

I'm on a business trip without my private laptop and SSH key. I'll amend the description and add additional log messages when I'm back at home.
