### ISSUE TITLE
Extension not compatible with Guacamole 1.0.0

### ISSUE THREAD

**Issue by pszabo891** [voegelas/guacamole-auth-pam#4]
The following error is thrown when trying to load the extension in Gaucamole 1.0.0.

`ERROR o.a.g.extension.ExtensionModule - Extension "guacamole-auth-pam-0.9.14.jar" could not be loaded: Extension "PAM Authentication Extension" is not compatible with this version of Guacamole.`

Are there any plans to upgrade it?

**Comment by voegelas** [comment]
I've created a new release.
